backend/app.py
backend/src/scraper/walmart_scraper.py
backend/src/summarize/summarize.py
backend/test/scraper/test_walmart_scraper.py

https://trello.com/c/qErk5MVh
- Summarize functionality shouldn't be an endpoint (moved to reviews on a WalmartProduct)
- Updated tests and functionality accordingly

Apply Summarize to Reviews

---

backend/app.py
backend/src/scraper/walmart_scraper.py
backend/src/scraper/youtube_scraper.py
backend/test/scraper/data/youtube/videos.py
backend/test/scraper/test_walmart_scraper.py
backend/test/scraper/test_youtube_scraper.py

https://trello.com/c/iBGqBuKp
- Added functionality to scrape YouTube using SerpAPI depending on the title of the product
- Added corresponding tests
- Moved summarization functionality from `walmart_scraper.py` into API call

Scraped YouTube Videos

---

backend/app.py
backend/src/scraper/google_shopping_scraper.py
backend/src/summarize/summarize.py
backend/test/scraper/data/google_shopping/products.py
backend/test/scraper/test_google_shopping_scraper.py

https://trello.com/c/HvdCL8ly
- Removed temp `/time` API
- Added functionality for pulling product data from Google Shopping

Add Product Search

---

frontend/src/App.js
frontend/src/components/Navbar.css
frontend/src/components/Navbar.js

N/A
- Added baseline navbar component

Baseline Navbar Component

---

backend/app.py
backend/dummy_data/dummy_product.py
backend/dummy_data/dummy_search_products.py

N/A
- Added dummy `product` data
- Added dummy `search-products` data

Dummy Data for Frontend Dev

---

frontend/src/components/search-bar/SearchBar.js
frontend/src/pages/product-search/ProductSearch.js

N/A
- Added connection to dummy backend endpoint for product search
- Added `SearchBar` component

Architecture for Product Search

---

backend/src/scraper/consumer_reports_scraper.py

- consumer_reports_scraper.py did not get pushed to main

Forgot consumer_reports_scraper

---

backend/app.py
frontend/src/components/ProductOption.css
frontend/src/components/ProductOption.jsx
frontend/src/pages/home/Home.jsx
frontend/src/pages/product-search/ProductSearch.jsx

https://trello.com/c/tvObxKc4
- Add ability to select/deselect products
- Each selected product is stored in the React state (when deselected, product is removed from state)
- Removed previous temporary `/time` endpoint
NOTE: No idea why the spacing looks weird in GitHub (doesn't look like that locally)

Clickable products

---

frontend/src/App.js
frontend/src/components/comparison/comparison-data/ReviewsData.jsx
frontend/src/components/comparison/comparison-data/SpecificationsData.jsx
frontend/src/components/comparison/comparison-data/VideosData.jsx
frontend/src/components/comparison/comparison-section/ComparisonSection.css
frontend/src/components/comparison/comparison-section/ComparisonSection.jsx
frontend/src/components/recommendation-table/RecommendationTable.jsx
frontend/src/pages/comparisons/Comparisons.jsx

https://trello.com/c/WA4pUVxy
- Added page for comparison table
- Added collapsible recommendations table with hardcoded data
- Added collapsible sections (specifications, reviews, and videos)
Still need to:
- Add dropdowns
- Have dropdowns call backend with different product to compare
- Add basic info section
- Add expert reviews

Comparison Table Framework

---

backend/app.py
backend/dummy_data/dummy_search_products.py
frontend/src/components/ProductOption.jsx
frontend/src/pages/home/Home.jsx
frontend/src/pages/product-search/ProductSearch.jsx

https://trello.com/c/WHoUSwvS
- Added temp backend data to help with frontend development
- Added ability to re-search for products (keeping track of previously selected products)
- [] Thorough automated tests have been added.

Re-search Products

---

README.md
backend/app.py
backend/requirements.txt
backend/src/scraper/bestbuy_scraper.py
backend/test/scraper/data/bestbuy/product_reviews.py
backend/test/scraper/test_bestbuy_scraper.py

https://trello.com/c/MyKC5E1x/107-scrape-reviews-from-best-buy
- Added Best Buy reviews to endpoint /api/bestbuy-product
- Added additional package to requirements.txt
- Added unit tests for endpoint
- Updated README with additional step to install NLTK dependencies
NOTE: Top positive and negative reviews are not provided by this API so I'm going to make another branch/PR for this functionality specifically.

adding best buy review scraping functionality

---

README.md
backend/requirements.txt

- Added requirements properly
- Updated README

Fixed requirements.txt and updated README

---

backend/app.py

N/A
- Having both `walmart-product` and `bestbuy-product` endpoints makes it a bit weird to reference from the frontend. To make the frontend load easier, idea is to have a single `product` endpoint which will use `cases` to determine which source it came from.
- I didn't remove the source specific endpoints yet (in case they're still being used for developing other features), but eventually these should be able to be removed.

Single Product Endpoint

---

backend/app.py
backend/dummy_data/dummy_preferences.py
backend/dummy_data/dummy_recommendation_products.py
backend/src/recommendations/recommendations.py
backend/src/scraper/bestbuy_scraper.py
backend/src/scraper/walmart_scraper.py
backend/test/recommendations/data/preferences.py
backend/test/recommendations/data/products.py
backend/test/recommendations/data/scraping.py
backend/test/recommendations/test_recommendations.py
backend/test/scraper/data/bestbuy/product_specs.py
backend/test/scraper/data/walmart/product_specs.py
backend/test/scraper/test_bestbuy_scraper.py
backend/test/scraper/test_walmart_scraper.py

https://trello.com/c/NodkHDRR/104-recommendation-engine-scrape-curated-lists
https://trello.com/c/d8W9jUsn/132-recommendation-engine-calculations-and-model
- Collected trending and most popular products from Best Buy
- Checked if Best Buy products were "Top Rated" or Walmart products were "Bestsellers" or "Customer Picks"
- Calculated the differences between user feature preferences and actual selected product features
- Calculated a score for each selected product
- Added automated tests
Note: I will improve how differences are identified during reading week. Also, we still have to figure out how data will be passed into the recommendation system (I have an idea but need to discuss it). Right now, dummy data is being fed in.

Recommendation system

---

backend/app.py
frontend/src/components/modals/base-modals/Modal.css
frontend/src/components/modals/base-modals/Modal.jsx
frontend/src/components/modals/content/feature-priority/FeaturePriorityModal.css
frontend/src/components/modals/content/feature-priority/FeaturePriorityModal.jsx
frontend/src/components/modals/content/preferences/PreferencesModal.css
frontend/src/components/modals/content/preferences/PreferencesModal.jsx
frontend/src/pages/comparisons/Comparisons.jsx
frontend/src/pages/product-search/ProductSearch.jsx

https://trello.com/c/rQaFl6fC
https://trello.com/c/bss0dvan
- Added modals for preferences and feature prioritization (I'm aware the code is redundant between the 2 modals; this is something I'll look to simplify over reading week)
- Connected E2E flow such that a user can start from search and end up on the comparison page
- Verified that all data is correctly passed through
NOTE: I'm still referencing the dummy endpoints, but I think this might be fine for PPC1. For PPC2 (when the app is hopefully fully completed), then we can reference actual endpoints
NOTE 2: I know Kejia shared the idea of moving the forms to the front of the flow, but since we don't have any designs for these yet I think it's fine to have them in the middle of the flow like we initially thought of. For PPC2 …

Preferences Form and E2E Flow

---

backend/app.py
backend/src/recommendations/recommendations.py
backend/test/recommendations/data/preferences.py

- Changed API call to POST and input data structure
- Inverted preferences dictionary to match frontend
- Updated tests

Fixed how recommendation API data is fed in

---

backend/dummy_data/dummy_product.py
frontend/src/components/comparison/comparison-data/BasicInfoData.jsx
frontend/src/components/comparison/comparison-data/ComparisonData.css
frontend/src/components/comparison/comparison-section/ComparisonSection.jsx
frontend/src/components/modals/content/feature-priority/FeaturePriorityModal.jsx
frontend/src/components/modals/content/preferences/PreferencesModal.jsx
frontend/src/pages/comparisons/Comparisons.jsx
frontend/src/pages/product-search/ProductSearch.jsx

- Added text from the Figma to better explain what's expected at each stage.
- Added basic info data to comparison table.

Additional flow details

---

frontend/src/components/modals/content/feature-priority/FeaturePriorityModal.jsx
frontend/src/components/modals/content/preferences/PreferencesModal.jsx
frontend/src/pages/comparisons/Comparisons.jsx
frontend/src/pages/product-search/ProductSearch.jsx

- Updated form contract for importance to have keys be numbers

Updated form contract

---

backend/app.py
backend/src/scraper/google_shopping_scraper.py
backend/test/scraper/test_google_shopping_scraper.py
frontend/src/pages/product-search/ProductSearch.jsx

https://trello.com/c/DC15TjND
- Updated backend `search-products` endpoint to include a `start` param which can be used for pagination/loading more products
- Added "Load More" button to frontend which calls the backend endpoint adding newly searched products to the existing list

Load more products

---

backend/dummy_data/dummy_product.py
backend/src/scraper/youtube_scraper.py
backend/test/scraper/data/youtube/videos.py
backend/test/scraper/test_youtube_scraper.py
frontend/package-lock.json
frontend/package.json
frontend/public/index.html
frontend/src/App.css
frontend/src/App.js
frontend/src/components/comparison/comparison-data/BasicInfoData.jsx
frontend/src/components/comparison/comparison-data/ComparisonData.css
frontend/src/components/comparison/comparison-data/MostReview.jsx
frontend/src/components/comparison/comparison-data/ReviewsData.jsx
frontend/src/components/comparison/comparison-data/SpecificationsData.jsx
frontend/src/components/comparison/comparison-data/SwitchProduct.jsx
frontend/src/components/comparison/comparison-data/VideosData.jsx
frontend/src/components/comparison/comparison-section/ComparisonSection.css
frontend/src/components/comparison/comparison-section/ComparisonSection.jsx
frontend/src/components/modals/form-modal/FormModal.css
frontend/src/components/modals/form-modal/FormModal.jsx
frontend/src/components/navbar/Navbar.css
frontend/src/components/product-option/ProductOption.jsx
frontend/src/components/search-bar/SearchBar.jsx
frontend/src/pages/comparisons/Comparisons.jsx
frontend/src/pages/product-search/ProductSearch.jsx
frontend/src/styles/buttons.css
frontend/test/components/comparison/comparison-data/BasicInfoData.test.js
frontend/test/components/comparison/comparison-data/MostReview.test.js
frontend/test/components/comparison/comparison-data/ReviewsData.test.js

https://trello.com/c/iJKji37M
- Added more fields to videos endpoint based on new design requirements/changes
- Added styling constants for all colours and fonts
- I'm aware that the font sizes may seem a bit large (I took the current values directly from Figma). Once I start adding more styling, I'll probably scale the font size down
- Imported `antd` library and started using it for star ratings and button components
- Updated tests based on new changes

Initial styling

---

.github/workflows/backend_tests.yml
.github/workflows/frontend_tests.yml

https://trello.com/c/1Ttw4mJ4
- Added workflow to run frontend tests
- Added workflow to run backend tests
Now, for each PR the following will appear. These 2 jobs just run the frontend/backend tests to ensure they all pass.

Workflow actions

---

frontend/src/App.css
frontend/src/App.js
frontend/src/components/logo/Logo.css
frontend/src/components/logo/Logo.jsx
frontend/src/components/navbar/Navbar.css
frontend/src/components/navbar/Navbar.jsx
frontend/src/components/recommendation-table/RecommendationTable.css
frontend/src/components/recommendation-table/RecommendationTable.jsx
frontend/src/pages/comparisons/Comparisons.css
frontend/src/pages/comparisons/Comparisons.jsx
frontend/src/pages/home/Home.jsx
frontend/src/pages/product-search/ProductSearch.jsx
frontend/src/styles/pages.css
frontend/test/components/logo/Logo.test.js
frontend/test/components/navbar/Navbar.test.js
frontend/test/components/recommendation-table/RecommendationTable.test.js

- Recommendation Table: https://trello.com/c/nWDUnTeS
- Navbar: https://trello.com/c/Du92IJfD
- Added logo component
- Added designs for navbar
- Added designs for recommendation table of comparisons page
NOTE: Please review https://github.com/tzada8/capstone/pull/42 first. A lot of the changes in this PR are actually from that other PR since I branched off of that branch instead of branching off main (I needed some styling in that branch and didn't want to wait for the PR to be merged). Once the other PR is reviewed and merged, a lot of the changes in this PR won't be shown anymore.

Table and navbar designs

---

frontend/src/components/footer/Footer.css
frontend/src/components/footer/Footer.jsx
frontend/src/pages/comparisons/Comparisons.jsx
frontend/src/pages/home/Home.jsx
frontend/src/pages/product-search/ProductSearch.jsx
frontend/test/components/footer/Footer.test.js

https://trello.com/c/JtZwJIkW
- Created basic footer component
- Used footer component across all pages

Basic footer component

---

backend/src/scraper/google_shopping_scraper.py
frontend/src/App.css
frontend/src/components/comparison/comparison-data/BasicInfoData.jsx
frontend/src/components/comparison/comparison-data/MostReview.jsx
frontend/src/components/footer/Footer.css
frontend/src/components/footer/Footer.jsx
frontend/src/components/product-option/ProductOption.css
frontend/src/components/product-option/ProductOption.jsx
frontend/src/components/rating/Rating.css
frontend/src/components/rating/Rating.jsx
frontend/src/components/search-bar/SearchBar.css
frontend/src/components/search-bar/SearchBar.jsx
frontend/src/pages/comparisons/Comparisons.css
frontend/src/pages/comparisons/Comparisons.jsx
frontend/src/pages/home/Home.jsx
frontend/src/pages/product-search/ProductSearch.css
frontend/src/pages/product-search/ProductSearch.jsx
frontend/src/styles/buttons.css
frontend/test/components/footer/Footer.test.js
frontend/test/components/product-option/ProductOption.test.js
frontend/test/components/rating/Rating.test.js

https://trello.com/c/hCQCcTDm
- Added TODO reminder for `/search-products` endpoint
- Added fixed buttons to bottom of product search page
- Added "Picked for you" section
- Added styling for search bar
- Added `Rating` component displaying rating, reviews, and star visualization
- Added styling for product options
- Added styling for Footer component

Product search designs

---

backend/app.py
frontend/src/components/loading/Loading.css
frontend/src/components/loading/Loading.jsx
frontend/src/pages/product-search/ProductSearch.jsx
frontend/test/components/loading/Loading.test.js

https://trello.com/c/zEZRGGou
- Added `Loading` component
- Implemented component when pulling products

Loading designs

---

frontend/src/components/comparison/comparison-data/BasicInfoData.jsx
frontend/src/components/comparison/comparison-data/ComparisonData.css
frontend/src/components/comparison/comparison-data/MostReview.jsx
frontend/src/components/comparison/comparison-data/ReviewsData.jsx
frontend/src/components/comparison/comparison-data/SpecificationsData.jsx
frontend/src/components/comparison/comparison-data/SwitchProduct.jsx
frontend/src/components/comparison/comparison-data/VideosData.jsx
frontend/src/components/comparison/comparison-section/ComparisonSection.css
frontend/src/components/comparison/comparison-section/ComparisonSection.jsx
frontend/src/components/recommendation-table/RecommendationTable.css
frontend/src/pages/comparisons/Comparisons.jsx
frontend/test/components/comparison/comparison-data/VideosData.test.js

https://trello.com/c/rhDGEM8t
- Updated styling for all components on the comparison page to generally match the designs
- Added fixed positioning for product switch dropdowns (still small edge case bugs, but general functionality finally works)

Comparison page designs

---

backend/src/scraper/google_shopping_scraper.py
frontend/src/App.css
frontend/src/components/comparison/comparison-data/ComparisonData.css
frontend/src/components/footer/Footer.css
frontend/src/components/footer/Footer.jsx
frontend/src/components/loading/Loading.css
frontend/src/components/modals/base-modal/Modal.css
frontend/src/components/product-option/ProductOption.css
frontend/src/components/product-option/ProductOption.jsx
frontend/src/components/rating/Rating.jsx
frontend/src/components/recommendation-table/RecommendationTable.css
frontend/src/pages/comparisons/Comparisons.jsx
frontend/src/pages/product-search/ProductSearch.css
frontend/src/pages/product-search/ProductSearch.jsx
frontend/src/styles/buttons.css

https://trello.com/c/yZTkgDFy
- Fixed small styling bugs including:
- Extra details from product source (e.g. before use to be `"Walmart - 33rd Street Camera"`, but now `"Walmart"`)
- Various sizing/spacing issues
- Hidding the product ratings if product has 0 ratings/reviews

Fixing styling bugs

---

frontend/.babelrc
frontend/package-lock.json
frontend/package.json
frontend/public/index.html
frontend/src/App.css
frontend/src/components/loading/Loading.css
frontend/src/components/loading/Loading.jsx
frontend/src/components/modals/content/feature-priority/FeaturePriorityModal.jsx
frontend/src/components/modals/content/preferences/PreferencesModal.jsx
frontend/src/components/navbar/Navbar.jsx
frontend/src/components/rating/Rating.css
frontend/src/components/rating/Rating.jsx
frontend/src/components/recommendation-table/RecommendationTable.css
frontend/src/components/recommendation-table/RecommendationTable.jsx
frontend/src/components/search-bar/SearchBar.css
frontend/src/components/search-bar/SearchBar.jsx
frontend/src/components/tooltip/Tooltip.css
frontend/src/components/tooltip/Tooltip.jsx
frontend/src/pages/comparisons/Comparisons.jsx
frontend/src/pages/home/Home.css
frontend/src/pages/home/Home.jsx
frontend/src/pages/product-search/ProductSearch.css
frontend/src/pages/product-search/ProductSearch.jsx
frontend/src/styles/buttons.css
frontend/test/components/rating/Rating.test.js
frontend/test/components/tooltip/Tooltip.test.js

https://trello.com/c/jOvLnSOk
Unfortunately, the `antd` library causes memory problems which was causing frontend deployments to crash... Their icon library is fine which I still use, but their component library cannot be used anymore. Thus, for the components where I was using an `antd` component, I need to convert them to a custom component. The specific `antd` components I was using before include:
- Buttons
- Progress for loading/fetching data from the backend
- Tooltip for explainability of "score" in recommendation table
- Star rating to show the rating for a product (e.g. 4.5 stars)

Fix frontend deployment

---

backend/dummy_data/dummy_preferences.py
backend/src/recommendations/recommendations.py
backend/test/recommendations/data/preferences.py
backend/test/recommendations/data/products.py
backend/test/recommendations/test_recommendations.py

https://trello.com/c/9iDoIJnR/168-recommendation-system-improvements-checks
- User can now skip the priority form
- Added product rating into the calculations
- Updated calculations to reflect preferences form options
- Improved product feature extraction logic
- Updated existing and added new tests

Recommendation system improvements

---

frontend/src/App.js
frontend/src/components/product-option/ProductOption.css
frontend/src/components/rating/Rating.css
frontend/src/components/scroll-to-top/ScrollToTop.jsx
frontend/src/pages/product-search/ProductSearch.css
frontend/src/pages/product-search/ProductSearch.jsx

https://trello.com/c/SKNTvf8B
- Turned product containers to `grid` display to ensure sizing is always the same
- Resolved warning where variable dependency wasn't mentioned in a useEffect
- Added component to always ensure pages start at the top

Resizing bugs

---

backend/src/scraper/bestbuy_scraper.py
backend/src/scraper/walmart_scraper.py
backend/test/scraper/data/walmart/product_reviews.py
backend/test/scraper/test_bestbuy_scraper.py

https://trello.com/c/heo0UABs/199-clip-best-buy-spec-list
- Shortened Best Buy specification list based on important attributes
- Removed null reviews from Walmart
- Changed Best Buy review error message to match Walmart

Fix backend issues

---

frontend/src/components/modals/base-modal/Modal.css
frontend/src/components/modals/content/feature-priority/FeaturePriorityModal.css
frontend/src/components/modals/content/feature-priority/FeaturePriorityModal.jsx

https://trello.com/c/dKKhFS0t
- Adjusted modal size depending on current screen size
- Added draggable icons
- Adjusted draggable functionality

Update priority form designs

---

frontend/src/pages/comparisons/Comparisons.jsx
frontend/src/pages/home/Home.css
frontend/src/pages/home/Home.jsx
frontend/src/pages/home/how-it-works/HowItWorks.jsx
frontend/src/pages/product-search/ProductSearch.jsx

https://trello.com/c/XhXBLwSE
- Hide "Picked for you" section if user skips form
- Added "Skip recommendations" functionality
- Hide spacing/text depending on selected path

Add secondary flow

---

frontend/src/components/comparison/comparison-data/ComparisonData.css
frontend/src/components/comparison/comparison-data/MostReview.jsx
frontend/src/components/comparison/comparison-data/ReviewsData.jsx

https://trello.com/c/1dvZxbgg
- Added ability to see "More" or "Less" text for the most positive review, most negative review, and expert review since there's a chance the info could be very long
- Also, I know the code is redundant (I implemented the exact same thing twice), but I think it's fine especially with the time constraints we have...

Reduce reviews wording

---

backend/app.py
backend/src/recommendations/recommendations.py
backend/src/scraper/bestbuy_scraper.py
backend/src/scraper/consumer_reports_scraper.py
backend/src/scraper/google_shopping_scraper.py
backend/src/scraper/walmart_scraper.py
backend/src/scraper/youtube_scraper.py
backend/src/summarize/summarize.py
backend/test/recommendations/data/scraping.py
backend/test/recommendations/test_recommendations.py
backend/test/scraper/data/bestbuy/product_reviews.py
backend/test/scraper/data/bestbuy/product_specs.py
backend/test/scraper/data/consumer_reports/expert_reviews.py
backend/test/scraper/data/google_shopping/products.py
backend/test/scraper/data/walmart/product_reviews.py
backend/test/scraper/data/walmart/product_specs.py
backend/test/scraper/data/youtube/videos.py
backend/test/scraper/test_bestbuy_scraper.py
backend/test/scraper/test_consumer_reports_scraper.py
backend/test/scraper/test_google_shopping_scraper.py
backend/test/scraper/test_walmart_scraper.py
backend/test/scraper/test_youtube_scraper.py

https://trello.com/c/0YIrsbaC/170-backend-edge-case-checks
- Added try, except blocks to all API calls
- Added conditions to check if errors are returned by API calls
- Updated existing tests and added new tests
Note: Currently logging all errors to a file but I wasn't sure if that was the best way of doing it. So it's kind of a temp solution at the moment.

Edge cases

---

backend/src/recommendations/recommendations.py
backend/src/scraper/bestbuy_scraper.py
backend/src/scraper/consumer_reports_scraper.py
backend/src/scraper/google_shopping_scraper.py
backend/src/scraper/walmart_scraper.py
backend/src/scraper/youtube_scraper.py

- Change double quotes to single

changed double quotes to single

---

backend/dummy_data/dummy_product.py
backend/src/summarize/summarize.py
frontend/src/components/comparison/comparison-data/ComparisonData.css
frontend/src/components/comparison/comparison-data/ReviewsData.jsx
frontend/src/components/comparison/comparison-section/ComparisonSection.css
frontend/src/components/navbar/Navbar.jsx
frontend/src/pages/comparisons/Comparisons.jsx
frontend/test/components/comparison/comparison-data/ReviewsData.test.js
frontend/test/components/navbar/Navbar.test.js

- https://trello.com/c/6zRiTsNf
- https://trello.com/c/JuuqrxA9
- Changed summarization to bulleted list
- Fixed 3 simple visual bugs
- When skipping comparisons, navbar still had blue background
- "More" button on reviews had background
- Comparison sections underline had border-radius
- Added text "Product has no reviews" if no review data

Update summarization and no reviews text

---

backend/dummy_data/dummy_product.py
backend/src/scraper/bestbuy_scraper.py
backend/src/scraper/google_shopping_scraper.py
backend/src/scraper/walmart_scraper.py
backend/src/scraper/youtube_scraper.py
backend/test/scraper/test_bestbuy_scraper.py
backend/test/scraper/test_google_shopping_scraper.py
backend/test/scraper/test_walmart_scraper.py

https://trello.com/c/68oWjY1b
- Several fields in the returned JSONs are passed but aren't needed. To reduce the amount of data transferred, these fields can be removed:
- Removed `ratings` (star count)
- Reduced number of YouTube videos to only top 3
- Removed `extensions` from product search
- Converted BestBuy images to be a list of strings (previously just returned a string)

Remove unused fields

---

backend/app.py
backend/src/scraper/bestbuy_scraper.py
backend/src/scraper/consumer_reports_scraper.py
backend/test/scraper/test_consumer_reports_scraper.py

https://trello.com/c/m6XmhLgf/229-consumer-report-link-403-error
https://trello.com/c/g9BUiDqd/162-general-issues
- Updated headers in Expert Reviews link check so 403 status is not returned
- Lowered similarity threshold from 75% to 65% for Best Buy reviews process
- Updated Expert Reviews logic so Best Buy UPC/Walmart ID don't have to match the expert review product (instead, the expert review product model name has to be in the selected product name)
- Updated existing tests

Fix links and update logic

---

backend/dummy_data/dummy_product.py
frontend/src/components/comparison/comparison-data/ComparisonData.css
frontend/src/components/comparison/comparison-data/ReviewsData.jsx

https://trello.com/c/StOfrtBB
- Fixed small bug about displaying expert reviews
- Converted review title to link if a link is provided, else displaying title as normal

Used link for expert reviews

---

backend/app.py
backend/src/recommendations/recommendations.py
backend/src/scraper/bestbuy_scraper.py
backend/src/scraper/consumer_reports_scraper.py
backend/src/scraper/google_shopping_scraper.py
backend/src/scraper/walmart_scraper.py
backend/src/scraper/youtube_scraper.py
backend/src/summarize/summarize.py

https://trello.com/c/SKGEcw04/241-logging-in-production
- Changed all logging.error statements to print statements (theoretically this will allow us to see logs in Render)

Render logging

---

backend/src/scraper/bestbuy_scraper.py
backend/test/scraper/data/bestbuy/product_reviews.py
backend/test/scraper/test_bestbuy_scraper.py

https://trello.com/c/i9PZTidg/247-backend-speed-up-best-buy-reviews
- Changed API request from pageSize 10 (default) to pageSize 100
- Removed pooling (since more reviews are being shown on one page, we don't need multiple queries)
- Updated existing tests

Speed up Best Buy review calls

---

frontend/src/components/comparison/comparison-data/BasicInfoData.jsx
frontend/src/components/comparison/comparison-data/ComparisonData.css
frontend/src/components/comparison/comparison-section/ComparisonSection.css
frontend/src/components/comparison/comparison-section/ComparisonSection.jsx
frontend/src/components/footer/Footer.css
frontend/src/components/logo/Logo.css
frontend/src/components/modals/base-modal/Modal.css
frontend/src/components/navbar/Navbar.css
frontend/src/components/recommendation-table/RecommendationTable.css
frontend/src/components/recommendation-table/RecommendationTable.jsx
frontend/src/components/tooltip/Tooltip.css
frontend/src/images/comparisons/caret-down-light.svg
frontend/src/pages/comparisons/Comparisons.css
frontend/src/pages/comparisons/Comparisons.jsx
frontend/src/pages/product-search/ProductSearch.jsx
frontend/src/styles/text.css
frontend/test/components/comparison/comparison-section/ComparisonSection.test.js

Cannot figure out how to pull the dynamic score from the backend; right now there is dummy text of "3.3" used as a placeholder for the values.
**Also will probably have to check how the merged navbar coexists with this version of the code?? Like to make sure the blue background works**
Also I figured out how to NOT commit the serpapi file changes YAY!
- Changed header of last page
- Changed font sizing

Comparion page frontend updates

---

frontend/src/components/modals/base-modal/Modal.css
frontend/src/components/modals/base-modal/Modal.jsx
frontend/src/components/modals/content/feature-priority/FeaturePriorityModal.jsx
frontend/src/components/modals/content/preferences/PreferencesModal.jsx
frontend/src/components/product-option/ProductOption.css
frontend/src/pages/home/Home.jsx
frontend/src/pages/product-search/ProductSearch.jsx
frontend/src/styles/buttons.css

https://trello.com/c/8aSZ3m4v
- Fixed modal buttons to bottom of screen (buttons are no longer part of the scrollable section)

Fix modal buttons

---

backend/app.py
frontend/src/components/comparison/comparison-data/VideosData.jsx
frontend/src/components/modals/content/feature-priority/FeaturePriorityModal.jsx
frontend/src/components/modals/content/preferences/PreferencesModal.jsx
frontend/src/pages/comparisons/Comparisons.jsx
frontend/src/pages/product-search/ProductSearch.jsx
frontend/test/components/loading/Loading.test.js

- Try/catch API calls: https://trello.com/c/TPjrPHP2
- Search bar loading: https://trello.com/c/RHmRkW0Y
- Cleanup warnings: https://trello.com/c/nE3atYW9
- Wrapped all API calls in try/catch blocks, so if backend server ever isn't running for some reason, at least frontend won't crash
- Adding loading display for product search page
- Resolved any warning messages

Frontend API edge cases

---

backend/app.py
backend/dummy_data/dummy_search_products.py
frontend/src/pages/comparisons/Comparisons.jsx

- Just went through the list of `TODOs` to make sure there weren't any major functionalities that require attention
- Left several `TODOs` since they're:
- Helpful comments when switching between hardcoded data and actual data
- Comments on future things for improving the app (e.g. making preferences form dynamic)

Resolve TODOs

---

frontend/src/components/comparison/comparison-data/BasicInfoData.jsx
frontend/src/components/comparison/comparison-data/ComparisonData.css
frontend/src/components/comparison/comparison-data/SwitchProduct.jsx
frontend/src/pages/comparisons/Comparisons.jsx
frontend/src/pages/product-search/ProductSearch.jsx

- Dynamic Scores: https://trello.com/c/ndEnqJOj
- Product Switch Dropdown: https://trello.com/c/4hiD2Hqx
- Added actual scores in place of temp hardcoded ones (`score` added to `basic_info` key of product dict)
- Updating scrolling for product switch dropdowns to correctly appear

Product switch fixes

---

frontend/public/index.html
frontend/src/App.css
frontend/src/components/comparison/comparison-data/MostReview.jsx
frontend/src/components/footer/Footer.jsx
frontend/src/components/navbar/Navbar.jsx
frontend/src/pages/comparisons/Comparisons.jsx
frontend/src/pages/home/Home.jsx
frontend/src/pages/home/data-pipeline/DataPipeline.jsx
frontend/src/pages/home/how-it-works/HowItWorks.jsx
frontend/src/pages/product-search/ProductSearch.jsx
frontend/src/routes/Routes.js
frontend/src/styles/text.css
frontend/test/components/comparison/comparison-data/MostReview.test.js
frontend/test/components/comparison/comparison-data/ReviewsData.test.js
frontend/test/components/footer/Footer.test.js
frontend/test/pages/home/data-pipeline/DataPipeline.test.js
frontend/test/pages/home/how-it-works/HowItWorks.test.js

https://trello.com/c/hvlkQpqF
- Change header font for letter `g`
- Fixed display logic for product switch dropdowns
- Updated text throughout to match Figma
- Updated `/our-data` route to `/instructions`

Text updates

---

frontend/src/pages/comparisons/Comparisons.jsx
frontend/src/pages/product-search/ProductSearch.jsx

https://trello.com/c/uO4qzgdZ
- Uncommented real endpoints
- Commented out dummy endpoints

Use real endpoints

---

backend/src/scraper/youtube_scraper.py
backend/test/scraper/test_youtube_scraper.py
frontend/src/pages/comparisons/Comparisons.jsx
frontend/src/pages/product-search/ProductSearch.jsx

https://trello.com/c/Xdk9mE1Q
- Default videos to list when errored
- Start pagination at 40 instead of 0
- Fix spelling typo

Prod bugfixes

---

frontend/src/components/comparison/comparison-data/VideosData.jsx
frontend/test/components/comparison/comparison-data/VideosData.test.js

https://trello.com/c/Xdk9mE1Q
- Display "No videos exist" if none returned

No videos text

---

frontend/src/pages/home/data-pipeline/DataPipeline.jsx

- Remove 'consumer report' from Data Pipeline text

Remove 'consumer report'

---

backend/src/recommendations/recommendations.py
backend/src/scraper/bestbuy_scraper.py
backend/src/scraper/walmart_scraper.py
frontend/src/components/comparison/comparison-data/ReviewsData.jsx
frontend/src/components/comparison/comparison-data/SummaryReviewsData.jsx

https://trello.com/c/5NzZGjlu
- Correctly covered `>45` megapixels case
- Added clearer message if no reviews exist for product
- Alphabetically sorted specs for easier comparison
I do remember there was a bug regarding `summary being undefined` but I haven't been able to reproduce it. If you remember how to reproduce that bug, then please let me know and I can add a fix for it in this PR.

Symposium bugfixes

---

README.md

- Updated frontend deploy from Heroku to Netlify

Update Frontend Deploy
